# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LED-ON-OFF.ui'
#
# Created: Mon Feb 24 00:48:06 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 745)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../tmp/led-red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 506, 729))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.spinPuerto = QtGui.QSpinBox(self.layoutWidget)
        self.spinPuerto.setMinimumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setWeight(75)
        font.setBold(True)
        self.spinPuerto.setFont(font)
        self.spinPuerto.setMinimum(0)
        self.spinPuerto.setMaximum(7)
        self.spinPuerto.setProperty("value", 7)
        self.spinPuerto.setObjectName("spinPuerto")
        self.verticalLayout.addWidget(self.spinPuerto)
        self.pushPuerto = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.pushPuerto.setFont(font)
        self.pushPuerto.setObjectName("pushPuerto")
        self.verticalLayout.addWidget(self.pushPuerto)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushManual = QtGui.QPushButton(self.layoutWidget)
        self.pushManual.setEnabled(True)
        self.pushManual.setMinimumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.pushManual.setFont(font)
        self.pushManual.setObjectName("pushManual")
        self.verticalLayout_10.addWidget(self.pushManual)
        self.pushAutomatic = QtGui.QPushButton(self.layoutWidget)
        self.pushAutomatic.setEnabled(True)
        self.pushAutomatic.setMinimumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.pushAutomatic.setFont(font)
        self.pushAutomatic.setObjectName("pushAutomatic")
        self.verticalLayout_10.addWidget(self.pushAutomatic)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout.addLayout(self.verticalLayout_12, 0, 5, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setEnabled(False)
        self.pushButton.setMinimumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setMinimumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dial_ON = QtGui.QDial(self.layoutWidget)
        self.dial_ON.setEnabled(False)
        self.dial_ON.setObjectName("dial_ON")
        self.verticalLayout_6.addWidget(self.dial_ON)
        self.lcd_ON = QtGui.QLCDNumber(self.layoutWidget)
        self.lcd_ON.setObjectName("lcd_ON")
        self.verticalLayout_6.addWidget(self.lcd_ON)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.dial_OFF = QtGui.QDial(self.layoutWidget)
        self.dial_OFF.setEnabled(False)
        self.dial_OFF.setObjectName("dial_OFF")
        self.verticalLayout_9.addWidget(self.dial_OFF)
        self.lcd_OFF = QtGui.QLCDNumber(self.layoutWidget)
        self.lcd_OFF.setObjectName("lcd_OFF")
        self.verticalLayout_9.addWidget(self.lcd_OFF)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 3, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.esc_10_ON = QtGui.QRadioButton(self.groupBox)
        self.esc_10_ON.setObjectName("esc_10_ON")
        self.verticalLayout_14.addWidget(self.esc_10_ON)
        self.esc_100_ON = QtGui.QRadioButton(self.groupBox)
        self.esc_100_ON.setObjectName("esc_100_ON")
        self.verticalLayout_14.addWidget(self.esc_100_ON)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.verticalLayout_11, 0, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.esc_10_OFF = QtGui.QRadioButton(self.groupBox_2)
        self.esc_10_OFF.setObjectName("esc_10_OFF")
        self.verticalLayout_15.addWidget(self.esc_10_OFF)
        self.esc_100_OFF = QtGui.QRadioButton(self.groupBox_2)
        self.esc_100_OFF.setObjectName("esc_100_OFF")
        self.verticalLayout_15.addWidget(self.esc_100_OFF)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_15)
        self.gridLayout.addWidget(self.groupBox_2, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.line_8 = QtGui.QFrame(self.layoutWidget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_3.addWidget(self.line_8)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.line_4 = QtGui.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.spinPuerto_A = QtGui.QSpinBox(self.layoutWidget)
        self.spinPuerto_A.setMinimumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setWeight(75)
        font.setBold(True)
        self.spinPuerto_A.setFont(font)
        self.spinPuerto_A.setMinimum(13)
        self.spinPuerto_A.setMaximum(17)
        self.spinPuerto_A.setProperty("value", 14)
        self.spinPuerto_A.setObjectName("spinPuerto_A")
        self.verticalLayout_4.addWidget(self.spinPuerto_A)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.radioButton_ON = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.radioButton_ON.setFont(font)
        self.radioButton_ON.setObjectName("radioButton_ON")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.radioButton_ON)
        self.radioButton_OFF = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.radioButton_OFF.setFont(font)
        self.radioButton_OFF.setChecked(True)
        self.radioButton_OFF.setObjectName("radioButton_OFF")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.radioButton_OFF)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.formLayout)
        self.pushPuertoA = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.pushPuertoA.setFont(font)
        self.pushPuertoA.setObjectName("pushPuertoA")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.pushPuertoA)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lcdAnalog = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdAnalog.setMinimumSize(QtCore.QSize(131, 51))
        self.lcdAnalog.setProperty("value", 0.0)
        self.lcdAnalog.setObjectName("lcdAnalog")
        self.verticalLayout_5.addWidget(self.lcdAnalog)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line_5 = QtGui.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.line_6 = QtGui.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.scrollArea = QtGui.QScrollArea(self.layoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 502, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.line_7 = QtGui.QFrame(self.layoutWidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), self.pushButton_2.raise_)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), self.pushButton.raise_)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Pinguino LED Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">ENTRADA ANALOGICA</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">SALIDA DIGITAL</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">ENTRADA ANALOGICA</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">PUERTO</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPuerto.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">CONFIRMAR</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPuerto.setText(QtGui.QApplication.translate("MainWindow", "CONFIRMAR", None, QtGui.QApplication.UnicodeUTF8))
        self.pushManual.setText(QtGui.QApplication.translate("MainWindow", "MANUAL", None, QtGui.QApplication.UnicodeUTF8))
        self.pushAutomatic.setText(QtGui.QApplication.translate("MainWindow", "AUTOMATICO", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "LED ON", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "LED OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">TIME ON</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">TIME ON</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">TIME ON</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">TIME OFF</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Escala ON", None, QtGui.QApplication.UnicodeUTF8))
        self.esc_10_ON.setText(QtGui.QApplication.translate("MainWindow", "x 10 ms", None, QtGui.QApplication.UnicodeUTF8))
        self.esc_100_ON.setText(QtGui.QApplication.translate("MainWindow", "x 100 ms", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Escala OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.esc_10_OFF.setText(QtGui.QApplication.translate("MainWindow", "x 10 ms", None, QtGui.QApplication.UnicodeUTF8))
        self.esc_100_OFF.setText(QtGui.QApplication.translate("MainWindow", "x 100 ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">ENTRADA ANALOGICA</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">ENTRADA ANALOGICA</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">ENTRADA ANALOGICA</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">PUERTO</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_ON.setText(QtGui.QApplication.translate("MainWindow", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_OFF.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPuertoA.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">CONFIRMAR</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPuertoA.setText(QtGui.QApplication.translate("MainWindow", "CONFIRMAR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">ENTRADA ANALOGICA</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">INFORMACIÓN</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "&SALIR", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Cristian Viola -- cristian_viola@hotmail.com.ar</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Cristian O. Viola (Argentina)  -- <a href=\"mailto:cristian_viola@hotmail.com.ar\"><span style=\" text-decoration: underline; color:#0000ff;\">Send mail</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

